//! `sync-agent-builds` — port of `scripts/sync_agent_builds.py`.
//!
//! Reads the registry agent registry and emits one `[[builds]]` entry per
//! agent whose `source.repo == "your-org/agents"`, byte-for-byte compatible
//! with the Python generator (only the header line names the new tool).

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

/// Build the generated-file body for a parsed registry. Kept separate so it can
/// be unit-tested without touching the filesystem.
fn render(registry: &toml::Value) -> (String, usize) {
    let agents = registry
        .get("agents")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();

    let mut out = String::new();
    out.push_str("# GENERATED by `propel-tools sync-agent-builds` — do not edit by hand.\n");
    out.push_str("# One [[builds]] per agent in the agent registry.\n\n");

    let mut count = 0;
    for agent in &agents {
        // `agent_id and repo == "your-org/agents" and path` — empty strings are
        // falsy in the Python original, so require non-empty here too.
        let agent_id = agent
            .get("id")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty());

        // `isinstance(source, dict)` — a non-table `source` is skipped.
        let source = match agent.get("source") {
            Some(v) if v.is_table() => v,
            _ => continue,
        };
        let repo = source.get("repo").and_then(|v| v.as_str());
        let path = source
            .get("path")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty());

        let (Some(id), Some("your-org/agents"), Some(path)) = (agent_id, repo, path) else {
            continue;
        };

        out.push_str("[[builds]]\n");
        out.push_str(&format!("name = \"{id}\"\n"));
        out.push_str("repo = \"agents\"\n");
        out.push_str(&format!("context = \"{path}\"\n"));
        out.push_str("isNixFlake = true\n");
        out.push_str(&format!(
            "nix_attr = \"packages.x86_64-linux.oci-image-{id}\"\n\n"
        ));
        count += 1;
    }

    (out, count)
}

pub fn sync_agent_builds(registry_path: &Path, out_path: &Path) -> Result<()> {
    let text = fs::read_to_string(registry_path)
        .with_context(|| format!("reading registry {}", registry_path.display()))?;
    let registry: toml::Value =
        toml::from_str(&text).with_context(|| "Error loading TOML file".to_string())?;

    let (body, count) = render(&registry);

    if let Some(parent) = out_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
        }
    }
    fs::write(out_path, body).with_context(|| format!("writing {}", out_path.display()))?;

    println!("wrote {} ({count} agent builds)", out_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn selects_only_agents_agents_with_a_path() {
        let registry: toml::Value = toml::from_str(
            r#"
            [[agents]]
            id = "code-review-agent"
            [agents.source]
            repo = "your-org/agents"
            path = "agents/github/code-review-agent"

            [[agents]]
            id = "external-thing"
            [agents.source]
            repo = "your-org/other"
            path = "x"

            [[agents]]
            id = "no-path"
            [agents.source]
            repo = "your-org/agents"

            [[agents]]
            id = "no-source"
            "#,
        )
        .unwrap();

        let (body, count) = render(&registry);
        assert_eq!(count, 1, "only the one agent with a path is included");
        assert!(body.contains("name = \"code-review-agent\""));
        assert!(body.contains("context = \"agents/github/code-review-agent\""));
        assert!(body.contains("nix_attr = \"packages.x86_64-linux.oci-image-code-review-agent\""));
        assert!(!body.contains("external-thing"));
        assert!(!body.contains("no-path"));
        assert!(!body.contains("no-source"));
    }

    #[test]
    fn exact_entry_format_matches_python() {
        let registry: toml::Value = toml::from_str(
            r#"
            [[agents]]
            id = "a"
            [agents.source]
            repo = "your-org/agents"
            path = "agents/x/a"
            "#,
        )
        .unwrap();
        let (body, _) = render(&registry);
        let expected = "\
# GENERATED by `propel-tools sync-agent-builds` — do not edit by hand.
# One [[builds]] per agent in the agent registry.

[[builds]]
name = \"a\"
repo = \"agents\"
context = \"agents/x/a\"
isNixFlake = true
nix_attr = \"packages.x86_64-linux.oci-image-a\"

";
        assert_eq!(body, expected);
    }
}
